"""
The SkyRig: the shared fighter skeleton (sky/skeleton.py), the 15 proxy
parts the game animates (named like Roblox R15 parts, one per joint), the
fighter build entry point and src/shared/FighterRigs.luau, the rig data the
game reads (joints, each fighter's proxy part boxes and sway chains).

Fighters themselves are skinned heroes built by sky/hero.py.
"""

import json
import os

from . import common, skeleton

PARTS = [
    "LowerTorso", "UpperTorso", "Head",
    "LeftUpperArm", "LeftLowerArm", "LeftHand",
    "RightUpperArm", "RightLowerArm", "RightHand",
    "LeftUpperLeg", "LeftLowerLeg", "LeftFoot",
    "RightUpperLeg", "RightLowerLeg", "RightFoot",
]

# (joint, part0, part1, pivot in rig space), parents first, and the grips:
# see sky/skeleton.py.
JOINTS = skeleton.JOINTS
JOINT_BY_NAME = {j[0]: j for j in JOINTS}
JOINT_OF_PART = {j[2]: j[0] for j in JOINTS}  # the joint that moves each part
PIVOT = skeleton.PIVOT

# Where a held weapon's grip sits, in rig space at rest (center of the fist).
# The weapon's +Y points forward (-Z) and its broad side (Z) points up, the
# same grip WeaponModels uses.
GRIP = skeleton.GRIP

FIGHTER_EXPORT_DIR = os.path.join(common.EXPORT_DIR, "fighters")


# FighterRigs.luau ---------------------------------------------------------------


def _lua_vec(v):
    return "{ " + ", ".join(_num(x) for x in v) + " }"


def _num(x):
    x = round(float(x), 3)
    if x == 0:
        x = 0.0
    text = f"{x:.3f}".rstrip("0").rstrip(".")
    return text if text not in ("-0", "") else "0"


def write_fighter_rigs_luau():
    """Regenerates src/shared/FighterRigs.luau from every exported fighter."""
    fighters = {}
    if os.path.isdir(FIGHTER_EXPORT_DIR):
        for file in sorted(os.listdir(FIGHTER_EXPORT_DIR)):
            if file.endswith(".json"):
                with open(os.path.join(FIGHTER_EXPORT_DIR, file)) as f:
                    info = json.load(f)
                fighters[info["name"]] = info

    lines = [
        "--[[",
        "    GENERATED by art/blender/build.py from the SkyRig. Do not edit by hand.",
        "",
        "    Skinned fighters are one skinned mesh whose bones carry the joint names;",
        "    Parts are the invisible proxy parts the game animates and holds weapons",
        "    with, and Sways are chains of extra bones (capes, hair, tails) the game",
        "    swings with springs. Bones are named <Name>1, <Name>2, ... down a chain.",
        "",
        "    Rig space: X = the fighter's right, Y = up, Z = behind (it faces -Z),",
        "    origin between the feet, 1 unit = 1 stud. Positions are { x, y, z }.",
        "    Joints are listed parents first; Part0 \"RigRoot\" is the invisible",
        "    root part the game welds to the HumanoidRootPart.",
        "]]",
        "",
        "return {",
        "\tJoints = {",
    ]
    for joint, part0, part1, pv in JOINTS:
        lines.append(f'\t\t{{ Name = "{joint}", Part0 = "{part0}", Part1 = "{part1}", Pivot = {_lua_vec(pv)} }},')
    lines += ["\t},", "\tGrip = {"]
    for side in ("Left", "Right"):
        hand = f"{side}Hand"
        lines.append(f'\t\t{side} = {{ Part = "{hand}", Position = {_lua_vec(GRIP[side])} }},')
    lines += ["\t},", f"\tMarkerDistance = {_num(common.MARKER_DISTANCE)},", "\tFighters = {"]
    for name, info in fighters.items():
        lines.append(f"\t\t{name} = {{")
        lines.append(f"\t\t\tHeight = {_num(info['height'])},")
        if "sways" in info:
            lines.append("\t\t\tSkinned = true,")
        lines.append("\t\t\tParts = {")
        for part in PARTS:
            b = info["parts"].get(part, {"center": [0, 3, 0], "size": [0.2, 0.2, 0.2]})
            lines.append(f"\t\t\t\t{part} = {{ Center = {_lua_vec(b['center'])}, Size = {_lua_vec(b['size'])} }},")
        lines.append("\t\t\t},")
        if "sways" in info:
            lines.append("\t\t\tSways = {")
            for sw in info["sways"]:
                lines.append("\t\t\t\t{")
                lines.append(f'\t\t\t\t\tName = "{sw["name"]}",')
                lines.append(f'\t\t\t\t\tParent = "{sw["parent"]}",')
                pts = ", ".join(_lua_vec(p) for p in sw["points"])
                if 20 + len(f"Points = {{ {pts} }},") <= 120:  # five tabs, within StyLua's column width
                    lines.append(f"\t\t\t\t\tPoints = {{ {pts} }},")
                else:
                    lines.append("\t\t\t\t\tPoints = {")
                    lines += [f"\t\t\t\t\t\t{_lua_vec(p)}," for p in sw["points"]]
                    lines.append("\t\t\t\t\t},")
                lines.append(f'\t\t\t\t\tStiffness = {_num(sw["stiffness"])},')
                lines.append(f'\t\t\t\t\tDamping = {_num(sw["damping"])},')
                lines.append(f'\t\t\t\t\tLimit = {_num(sw["limit"])},')
                if sw.get("behind") is not None:
                    lines.append(f'\t\t\t\t\tBehind = {_num(sw["behind"])},')
                lines.append("\t\t\t\t},")
            lines.append("\t\t\t},")
        lines.append("\t\t},")
    lines += ["\t},", "}", ""]
    path = os.path.join(common.SHARED_SRC, "FighterRigs.luau")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {path} ({len(fighters)} fighters)")
    return path


def build_fighter(module):
    """Runs a fighter script (art/blender/fighters/<name>.py): builds the
    skinned hero, exports it and renders its turnaround. Returns the export
    info."""
    from . import hero

    return hero.build(module)


__all__ = ["PARTS", "JOINTS", "JOINT_OF_PART", "PIVOT", "GRIP", "write_fighter_rigs_luau", "build_fighter"]
