"""
rigging.py - a skeleton (bones + skin weights) for every Steal a Sock model, so the game can bend
them: noodle legs, tapping feet, flopping cuffs, waving tentacles, a talking puppet mouth.

`rig_sock(objs)` runs in build_all.py right after texturing.bake and before the export. It only adds
an armature object `<Name>_Rig`, vertex groups and an Armature modifier on the body and on the
`_Outline` hull: no vertex moves, so the rest pose is exactly the built (and baked) model, and the
bake's UVs and image are untouched. The GLB then carries ONE glTF skin used by both meshes.

Bone convention (src/shared/Config/SockRigConfig.luau, generated by `write_luau_config`, mirrors it):
- `Root` at the `_Base` marker, no vertex weights (Roblox rule).
- `Leg1` -> `Leg2` -> `Leg3` -> `Leg4` up the leg axis from the ankle to the cuff (a single's
  lower bones stand on its sack's leaning centre line); `Leg4` is the "head" block: it starts just
  under the googly eyes, so the face never bends. `Cuff` (child of Leg4) is the top band and the
  rolled lip.
- `Foot` (child of Leg1, from the ankle along the foot's centre line) and `Toe` (child of Foot, the
  toe cap). Singles (Socktopus, LostSock) have no foot.
- `Eye1`, `Eye2` (viewer's left first) at the eyeball centres pointing out of the eye; only the
  PUPIL rides on them, so turning one about its own axis rolls the pupil round the googly eye.
- Extras per type, each a child of what it sits on: `Hat`, `Jaw`, `Pogo`, `Monocle`, `Beard`,
  `Armor`, `Cape`, `Bills`, `Question`, `Stink`, `Fly1..3`, `Toe1..5`, `Tent<i>_<j>`,
  `Neck1..4` + `Head`, `Lake`, `Hump1..2`, `Tail` (see the per-type functions below).
- Axes (Blender bone axes, kept by the glTF exporter): local +Y runs along the bone (head -> tail),
  local +Z points to the sock's FRONT (the face: Blender -Y, Roblox/glTF +Z) as far as the bone
  allows, local +X = Y x Z. Bones that point along the front (Eye, Monocle) use local +Z = up.
  So every Leg / Cuff / Root / Jaw bone has NO rest rotation: its local axes are the model's axes.
- The armature object is at the origin, unrotated, unit scale; the body and outline are parented
  to it (the glTF exporter's canonical skinned-mesh layout), the markers are not.

Weights (at most 4 bones per vertex, normalized):
- The body: a smooth field. Up the leg each vertex blends the two nearest chain bones by height
  (smoothstep across a band round each joint; the eyes and the cuff band sit outside the bands).
  Round the instep the leg turns into the foot along the same fan of rings the body is built
  with (angle about the instep centre), and along the foot Foot hands over to Toe at the toe cap.
- Pieces that lie on the surface (stripes, decals, toga, sweatband, lint pads, drawn lines) use
  the same field per vertex, so they bend with the skin under them.
- Rigid features (eyes, rims, lids, monocles, hats, headphones, the pogo stick, beards, armour,
  fangs, buttons ...) are weighted 100% to one bone, so they never stretch or shear.
- Small stuck-on bits (sweat drops, crumbs, bolts, fins, a brooch) get the field's weights at ONE
  anchor point for every vertex: they ride the surface where they are glued, without stretching.
- Chains (tentacles, the neck) blend along their own centre line; a tether (a monocle chain, the
  dryer-sheet cape, long yarn strands) blends from its bone at one end to the skin at the other.
- The outline hull copies its weights vertex for vertex from the body piece it was inflated from
  (sockkit.finish records which vertex came from which piece), so hull and body always bend alike.
"""
import math

import bpy
import numpy as np
from mathutils import Matrix, Vector

import sockkit as K

FRONT = Vector((0.0, -1.0, 0.0))     # the face side (Roblox +Z)
UP = Vector((0.0, 0.0, 1.0))
MAX_INF = 4                          # Roblox: at most 4 bones per vertex
MIN_W = 0.004                        # weights below this are dropped (then renormalised)
CHAIN = ("Leg1", "Leg2", "Leg3", "Leg4", "Cuff")


def _smooth(t):
    t = min(max(t, 0.0), 1.0)
    return t * t * (3.0 - 2.0 * t)


def _add(out, b, w):
    if w > 0.0:
        out[b] = out.get(b, 0.0) + w


def _mix(a, b, t):
    """Weights a * (1 - t) + b * t."""
    out = {}
    for k, v in a.items():
        _add(out, k, v * (1.0 - t))
    for k, v in b.items():
        _add(out, k, v * t)
    return out


def _finalise(w):
    """At most MAX_INF influences, tiny ones dropped, normalised; never the Root."""
    items = sorted(((v, k) for k, v in w.items() if k != "Root" and v > 0.0), reverse=True)[:MAX_INF]
    items = [(v, k) for v, k in items if v >= MIN_W] or items[:1]
    tot = sum(v for v, _k in items)
    return {k: v / tot for v, k in items}


# ------------------------------------------------------------------ bones
class Bone:
    def __init__(self, name, parent, head, tail, role, index=None, seg=None, hint=None):
        self.name, self.parent, self.role, self.index, self.seg = name, parent, role, index, seg
        self.hint = hint or {}        # e.g. a Jaw's {turn = max degrees about +X, slide = max studs}
        self.head, self.tail = Vector(head), Vector(tail)
        if (self.tail - self.head).length < 0.05:            # Blender drops zero-length bones
            self.tail = self.head + UP * 0.2

    @property
    def length(self):
        return (self.tail - self.head).length


# ------------------------------------------------------------------ chains (tentacles, the neck)
class Chain:
    """Weights along a centre line `path`: bone k owns arc length knots[k]..knots[k+1], blending
    over +-blend * segment round each inner knot. Below root_blend (lo, hi) the vertex hands over
    from `base(p)` (the body it grows out of) to the first bone; past end_blend (lo, hi, bone) it
    hands over to `bone` (the neck into the Head)."""

    def __init__(self, path, bones, knots, base, root_blend=None, end_blend=None, blend=0.35):
        self.P = np.array([tuple(p) for p in path], np.float64)
        seg = np.linalg.norm(self.P[1:] - self.P[:-1], axis=1)
        self.cum = np.concatenate([[0.0], np.cumsum(seg)])
        self.bones, self.knots, self.base = bones, knots, base
        self.root_blend, self.end_blend, self.blend = root_blend, end_blend, blend

    def length(self):
        return float(self.cum[-1])

    def at(self, s):
        """Point on the path at arc length s."""
        s = min(max(s, 0.0), self.cum[-1])
        k = int(min(np.searchsorted(self.cum, s, side="right") - 1, len(self.P) - 2))
        t = (s - self.cum[k]) / max(self.cum[k + 1] - self.cum[k], 1e-9)
        return Vector(self.P[k] * (1 - t) + self.P[k + 1] * t)

    def arc_of(self, pts):
        """Arc length of the nearest path point for each point (n, 3) -> (n,)."""
        X = np.asarray(pts, np.float64)[:, None, :]
        A, B = self.P[None, :-1, :], self.P[None, 1:, :]
        AB = B - A
        t = np.clip(((X - A) * AB).sum(-1) / np.maximum((AB * AB).sum(-1), 1e-12), 0.0, 1.0)
        D = ((A + AB * t[..., None] - X) ** 2).sum(-1)
        k = D.argmin(axis=1)
        rows = np.arange(len(k))
        return self.cum[k] + t[rows, k] * (self.cum[k + 1] - self.cum[k])

    def weights(self, p, s):
        kn, bones = self.knots, self.bones
        w = {bones[0]: 1.0}
        for j in range(1, len(bones)):
            half = self.blend * min(kn[j] - kn[j - 1], kn[j + 1] - kn[j])
            if s >= kn[j] - half:
                t = _smooth((s - (kn[j] - half)) / (2 * half))
                w = {bones[j - 1]: 1.0 - t, bones[j]: t}
        if self.root_blend and s < self.root_blend[1]:
            lo, hi = self.root_blend
            w = _mix(self.base(p), w, _smooth((s - lo) / (hi - lo)))
        if self.end_blend and s > self.end_blend[0]:
            lo, hi, b = self.end_blend
            w = _mix(w, {b: 1.0}, _smooth((s - lo) / (hi - lo)))
        return w


# ------------------------------------------------------------------ the plan for one sock
class Rig:
    """Bones + how every piece is weighted, for one built sock (SockCtx `c`, body object)."""

    def __init__(self, c, body, info):
        self.c, self.body, self.info = c, body, info
        n = len(body.data.vertices)
        co = np.empty(n * 3, np.float32)
        body.data.vertices.foreach_get("co", co)
        mw = np.array(body.matrix_world, np.float64)
        co = co.reshape(-1, 3).astype(np.float64) @ mw[:3, :3].T + mw[:3, 3]
        self.co = co
        self.bones = {}
        self.assign = {}              # piece index -> target
        self.field = self.base        # the skin field (types may wrap it)
        self.eye_parent = "Leg4"
        self.cuff_bone = "Cuff"       # Sockington: the helm holds the cuff still
        self._setup_field()

    # -- pieces
    def idx(self, names, group=None, where=None):
        names = names.split() if isinstance(names, str) else names
        lo, hi = self.c.face_range
        out = []
        for i, nm in enumerate(self.info["names"]):
            if nm not in names or self.info["body"][i] is None:
                continue
            g = "body" if i < lo else ("face" if i < hi else "feat")
            if group and g != group:
                continue
            if where and not where(self.cen([i])):
                continue
            out.append(i)
        return out

    def verts(self, idxs):
        rs = [self.info["body"][i] for i in idxs]
        return np.concatenate([self.co[s:s + n] for s, n in rs]) if rs else np.zeros((0, 3))

    def cen(self, idxs):
        v = self.verts(idxs)
        return Vector(v.mean(axis=0)) if len(v) else Vector()

    def lo(self, idxs):
        return Vector(self.verts(idxs).min(axis=0))

    def hi(self, idxs):
        return Vector(self.verts(idxs).max(axis=0))

    def put(self, idxs, target):
        for i in idxs:
            self.assign[i] = target

    # -- bones
    def add(self, name, parent, head, tail, role, index=None, seg=None, hint=None):
        self.bones[name] = Bone(name, parent, head, tail, role, index, seg, hint)
        return self.bones[name]

    def dominant(self, p):
        w = self.base(p)
        return max(w, key=w.get)

    # -- the skin field
    def _setup_field(self):
        c, sh = self.c, self.c.shape
        h, cz = c.h, c.cuff_z
        self.footed = c.side != "S"
        self.d = c.d if c.d else 1.0
        z0 = sh.Pa.y if self.footed else sh.z_bot
        on_leg = [e for e in c.eyes if e[2] < h]          # SockNess carries its eyes on the head
        self.eye_lo = min(e[2] for e in on_leg) - c.eye_rim_r if on_leg else None
        self.eye_hi = max(e[2] for e in on_leg) + c.eye_rim_r if on_leg else None
        z3 = self.eye_lo - 0.2 if on_leg else z0 + 0.72 * (cz - z0)
        if self.footed:    # Leg1 = the ankle (up to the instep), Leg2 / Leg3 share the shin
            z1 = min(max(c.instep_z - 0.1, z0 + 0.3 * (z3 - z0)), z0 + 0.5 * (z3 - z0))
            z2 = (z1 + z3) / 2
        else:              # singles: the wide sack bends evenly (narrow bands would crease it)
            z1, z2 = z0 + (z3 - z0) / 3, z0 + 2 * (z3 - z0) / 3
        self.zs = [z0, z1, z2, z3, cz, h]
        # blend bands: as wide as the segments allow (they touch), except that the eyes and the
        # cuff band stay outside them (the face never bends, the cuff flops as one ring)
        up3 = 0.5 * (cz - z3)
        if on_leg:
            up3 = min(up3, self.eye_lo - z3 - 0.02)
        lo4 = min(max(cz - self.eye_hi - 0.03, 0.04), 0.15) if on_leg else 0.15
        b1, b2 = 0.5 * min(z1 - z0, z2 - z1), 0.5 * min(z2 - z1, z3 - z2)
        self.zones = [(z1 - b1, z1 + b1), (z2 - b2, z2 + b2), (z3 - 0.5 * (z3 - z2), z3 + up3),
                      (cz - lo4, cz + min(0.1, 0.45 * (h - cz)))]
        if self.footed:
            self.Q, self.Pa, self.ax = sh.Q.copy(), sh.Pa.copy(), sh.ax.copy()
            self.th_end = math.pi / 2 - sh.alpha
            self.t1, self.t_tip = sh.t1, sh.t_tip
            self.bt = min(0.15, 0.4 * (sh.t_tip - sh.t1))

    def leg(self, z):
        bones = CHAIN[:4] + (self.cuff_bone,)
        for j, (a, b) in enumerate(self.zones):
            if z < a:
                return {bones[j]: 1.0}
            if z <= b:
                t = _smooth((z - a) / (b - a))
                return {bones[j]: 1.0 - t, bones[j + 1]: t} if bones[j] != bones[j + 1] else {bones[j]: 1.0}
        return {bones[4]: 1.0}

    def foot(self, p):
        """(foot share, toe share of the foot) at p: the angle about the instep centre (the fan the
        body's rings are built on) hands the leg over to the foot."""
        if not self.footed:
            return 0.0, 0.0
        x, z = self.d * p[0], p[2]
        th = math.atan2(-(z - self.Q.y), -(x - self.Q.x))
        if th <= 0.0:
            return 0.0, 0.0
        wf = _smooth((th / self.th_end - 0.1) / 0.75)
        ta = (x - self.Pa.x) * self.ax.x + (z - self.Pa.y) * self.ax.y
        wt = _smooth((ta - (self.t1 - self.bt)) / (2 * self.bt))
        return wf, wt

    def base(self, p):
        wf, wt = self.foot(p)
        out = {}
        if wf < 1.0:
            for b, w in self.leg(p[2]).items():
                _add(out, b, w * (1.0 - wf))
        _add(out, "Foot", wf * (1.0 - wt))
        _add(out, "Toe", wf * wt)
        return out

    # -- standard bones
    def standard_bones(self):
        c, sh = self.c, self.c.shape
        z0, z1, z2, z3, z4, h = self.zs
        base_z = getattr(c, "base_z", 0.0)
        ank = Vector((0.0, 0.0, z0))
        self.add("Root", None, (0, 0, base_z), ank if z0 > base_z + 0.1 else (0, 0, base_z + 0.3), "root")
        for k, (a, b) in enumerate(((z0, z1), (z1, z2), (z2, z3), (z3, z4))):
            x, y = self.axis_at(a)
            self.add(f"Leg{k + 1}", "Root" if k == 0 else f"Leg{k}", (x, y, a), (x, y, b), "leg", index=k + 1)
        self.add("Cuff", "Leg4", (0, 0, z4), (0, 0, h), "cuff")
        if self.footed:
            d = self.d
            tp = sh.Pa + sh.ax * sh.t1
            self.add("Foot", "Leg1", ank, (d * tp.x, 0.0, tp.y), "foot")
            self.add("Toe", "Foot", (d * tp.x, 0.0, tp.y), c.toe_tip, "toe")

    def axis_at(self, z):
        """(x, y) of the leg's centre line at height z: the leg axis, except down a single's sack,
        whose centre slides toward the front-left (socks._Shape._bulb_rings). The leg bones stay
        upright (no rest rotation); they just pivot about the real middle of the sack."""
        sh = self.c.shape
        if self.footed:
            return 0.0, 0.0
        k = _smooth((sh.z_swell - z) / max(sh.z_swell - sh.z_bulb, 0.1))
        return sh.lean.x * k, sh.lean.y * k

    def eye_bones(self):
        c = self.c
        for i, (e, n) in enumerate(zip(c.eyes, c.eye_n)):
            self.add(f"Eye{i + 1}", self.eye_parent, e, Vector(e) + Vector(n).normalized() * 0.25, "eye", index=i + 1)

    def nearest_bone(self, p, prefix):
        cands = [b for b in self.bones.values() if b.name.startswith(prefix)]
        return min(cands, key=lambda b: (b.head - p).length).name

    def default_assign(self):
        """Pieces no type function claimed: the shared face and everything lying on the skin."""
        lo, hi = self.c.face_range
        for i, nm in enumerate(self.info["names"]):
            if i in self.assign:
                continue
            face = lo <= i < hi
            if i == 0:
                t = ("skin",)
            elif nm == "pupil" and any(b.role == "eye" for b in self.bones.values()):
                t = ("eye",)
            elif nm in ("eye", "eyerim", "lid", "lidline", "eyelid") or (nm == "glint" and face):
                t = ("bone", self.eye_parent)
            elif nm == "glint":
                t = ("stuck", None)
            else:
                t = ("skin",)
            self.assign[i] = t

    # -- weights
    def piece_weights(self, i, pts):
        t = self.assign[i]
        kind = t[0]
        if kind == "bone":
            return [{t[1]: 1.0}] * len(pts)
        if kind == "eye":
            cen = Vector(pts.mean(axis=0))
            return [{self.nearest_bone(cen, "Eye"): 1.0}] * len(pts)
        if kind == "near":                                 # rigid to the nearest bone named prefix*
            cen = Vector(pts.mean(axis=0))
            return [{self.nearest_bone(cen, t[1]): 1.0}] * len(pts)
        if kind == "stuck":                                # ("stuck", anchor or None[, "base"])
            anchor = t[1] if t[1] is not None else Vector(pts.mean(axis=0))
            fn = self.base if len(t) > 2 and t[2] == "base" else self.field
            return [fn(anchor)] * len(pts)
        if kind == "tether":                               # bone at height z_bone, skin at z_skin
            _k, b, z_bone, z_skin = t
            out = []
            for p in pts:
                f = _smooth((p[2] - z_skin) / (z_bone - z_skin))
                out.append(_mix(self.field(p), {b: 1.0}, f))
            return out
        if kind == "chain":
            ch = t[1]
            s = ch.arc_of(pts)
            return [ch.weights(p, si) for p, si in zip(pts, s)]
        return [self.field(p) for p in pts]               # skin

    def all_weights(self):
        """-> (body weights [dict per vertex], outline weights) from the assignments."""
        n = len(self.co)
        W = [None] * n
        for i, r in enumerate(self.info["body"]):
            if r is None:
                continue
            s, cnt = r
            for k, w in enumerate(self.piece_weights(i, self.co[s:s + cnt])):
                W[s + k] = _finalise(w)
        missing = [k for k, w in enumerate(W) if w is None]
        assert not missing, f"{len(missing)} body vertices without weights"
        return W


# ------------------------------------------------------------------ per-type extras
def _hat(R, names, parent):
    """A Hat bone on the rim's centre (where a hat rests), pointing up; the pieces ride on it."""
    ids = R.idx(names)
    h = R.c.h
    R.add("Hat", parent, (0, 0, h), (0, 0, max(R.hi(ids).z, h + 0.3)), "hat")
    R.put(ids, ("bone", "Hat"))
    return ids


def _monocle(R, ring, parts, chain, loop):
    c = R.c
    ids = R.idx(ring, "feat")
    ctr = R.cen(ids)
    e = min(range(len(c.eyes)), key=lambda i: (Vector(c.eyes[i]) - ctr).length)
    n = Vector(c.eye_n[e]).normalized()
    R.add("Monocle", R.eye_parent, ctr, ctr + n * 0.3, "accessory")
    R.put(ids + R.idx(parts, "feat"), ("bone", "Monocle"))
    z_knob = R.cen(R.idx("knob")).z
    z_loop = R.cen(R.idx(loop)).z
    R.put(R.idx(chain), ("tether", "Monocle", z_knob, z_loop))
    R.put(R.idx(loop), ("stuck", None))


def _anklebiter(R):
    ids = R.idx("fang fang_ink")
    zt = R.hi(ids).z
    # like the Puppet's: an upright bone hinged 2 units behind the grin line, so turning it about +X
    # (or sliding it down its -Y) drops the fangs a little - a chomp
    R.add("Jaw", R.dominant(Vector((0.0, 0.0, zt))), (0.0, 2.0, zt), (0.0, 2.0, zt + 0.3), "jaw",
          hint=dict(turn=4, slide=0.12))
    R.put(ids, ("bone", "Jaw"))


def _argylo(R):
    _monocle(R, "monocle", "monocle_ink lens glint knob", "chain", "loop")


def _zillionaire(R):
    _hat(R, "hatinside tophat hatband", "Cuff")
    top = R.hi(R.idx("tophat")).z

    def tucked(p):           # the bill tucked in the hat band (the others are the fountain)
        return math.hypot(p.x, p.y) < 1.2 and p.z < top - 0.6

    bills = R.idx("bill billoval billdot")
    R.put([i for i in bills if tucked(R.cen([i]))], ("bone", "Hat"))
    R.add("Bills", "Hat", (0, 0, top), (0, 0, top + 0.6), "accessory")
    R.put([i for i in bills if not tucked(R.cen([i]))], ("bone", "Bills"))
    _monocle(R, "monocle", "glint knob", "chain", "chainloop")


def _sockrates(R):
    c = R.c
    ids = R.idx("beard beard_ink plate_ink plate moustache")
    zt = R.hi(R.idx("moustache")).z
    head = Vector((0.0, c.front(0.0, zt)[1], zt))
    lo = R.lo(R.idx("beard"))
    R.add("Beard", R.dominant(head), head, (0.0, R.cen(R.idx("beard")).y, lo.z), "accessory")
    R.put(ids, ("bone", "Beard"))
    _hat(R, "leaf leaf_ink stem", "Leg4")
    R.put(R.idx("brooch shine"), ("stuck", R.cen(R.idx("brooch"))))


def _toetoe(R):
    for k, i in enumerate(R.idx("toe", "feat")):
        tg = R.info["tags"][i]
        R.add(f"Toe{k + 1}", "Toe", tg["head"], tg["tail"], "digit", index=k + 1)
        R.put([i], ("bone", f"Toe{k + 1}"))


def _sockhopper(R):
    c = R.c
    pole = R.cen(R.idx("pole"))
    zb = R.cen(R.idx("handlebar")).z
    R.add("Pogo", "Root", (pole.x, pole.y, getattr(c, "base_z", 0.0)), (pole.x, pole.y, zb), "pogo")
    R.put(R.idx("pole handlebar sleeve plank shaft tip"), ("bone", "Pogo"))


def _djdryer(R):
    _hat(R, "cushion cup cupcap headband", "Leg4")
    R.put(R.idx("lens bridge arm glint", "feat"), ("bone", "Leg4"))
    R.put(R.idx("knot tieend"), ("stuck", R.cen(R.idx("knot"))))
    cape = R.idx("cape")
    v = R.verts(cape)
    zt, zb = v[:, 2].max(), v[:, 2].min()
    top = v[v[:, 2] > zt - 0.15].mean(axis=0)
    bot = v[v[:, 2] < zb + 0.15].mean(axis=0)
    head = Vector((0.0, top[1], zt))
    R.add("Cape", R.dominant(head), head, (0.0, bot[1], zb), "accessory")
    R.put(cape + R.idx("sheetdot"), ("tether", "Cape", zb, zt))


def _socktopus(R):
    for i, pi in enumerate(R.idx("tentacle", "feat")):
        tg = R.info["tags"][pi]
        names = [f"Tent{i + 1}_{j}" for j in (1, 2, 3)]
        tmp = Chain(tg["path"], names, [0, 1, 2, 3], R.base)
        s0 = float(tmp.arc_of([tuple(tg["root"])])[0])
        L = tmp.length()
        kn = [s0 + (L - s0) * j / 3 for j in range(4)]
        ch = Chain(tg["path"], names, kn, R.field, root_blend=(s0 - 0.12, s0 + 0.1))
        for j in range(3):
            R.add(names[j], "Leg1" if j == 0 else names[j - 1], ch.at(kn[j]), ch.at(kn[j + 1]), "tentacle",
                  index=i + 1, seg=j + 1)
        R.put([pi], ("chain", ch))


def _sockington(R):
    R.cuff_bone = "Leg4"                     # the helm covers the cuff: no cuff flop inside it
    _hat(R, "helm dome helmtrim browband nasal plumeholder plume", "Leg4")
    ids = R.idx("breastplate platetrim plateside strap emblem_ink emblem emblem_in")
    v = R.verts(R.idx("breastplate"))
    head = Vector((0.0, 0.0, v[:, 2].max()))
    R.add("Armor", R.dominant(head), head, (0.0, 0.0, v[:, 2].min()), "accessory")
    R.put(ids, ("bone", "Armor"))


def _stinkolino(R):
    c, h = R.c, R.c.h
    toe = Vector(c.toe_tip) if c.FOOT else Vector((0, 0, -9))
    near_toe = [i for i in R.idx("gas stink") if (R.cen([i]) - toe).length < 1.4]
    R.put(near_toe, ("bone", "Toe"))
    R.add("Stink", "Cuff", (0, 0, h), (0, 0, h + 1.0), "accessory")
    R.put([i for i in R.idx("gas stink") if i not in near_toe], ("bone", "Stink"))
    flies = R.idx("fly")
    heads = R.idx("flyhead")
    for k, i in enumerate(flies):
        p = R.cen([i])
        hd = min((R.cen([j]) for j in heads), key=lambda q: (q - p).length)
        R.add(f"Fly{k + 1}", "Root", p, p + (hd - p).normalized() * 0.3, "fly", index=k + 1)
        R.put([i], ("bone", f"Fly{k + 1}"))
    R.put(R.idx("flyhead flyeye wing trail"), ("near", "Fly"))
    tongue = R.cen(R.idx("tongue"))
    R.put(R.idx("tongue crease"), ("stuck", tongue))


def _sockness(R):
    c, h = R.c, R.c.h
    hp = R.idx("head")[0]
    tg_head = R.info["tags"][hp]
    neck = R.idx("neck")[0]
    path = R.info["tags"][neck]["path"]
    tmp = Chain(path, ["x"], [0, 1], R.base)
    cum = tmp.cum
    s_rim = next(float(cum[k]) for k in range(len(path)) if path[k].z > h)
    s_end = tmp.length()
    C1 = Vector(tg_head["cranium"])
    # where the neck's centre line enters the cranium (the visible neck ends there)
    s_in = next((float(cum[k]) for k in range(len(path)) if (path[k] - C1).length < 0.6), s_end)
    names = ["Neck1", "Neck2", "Neck3", "Neck4"]
    kn = [s_rim + (s_in - s_rim) * j / 4 for j in range(5)]
    base = R.base
    ch = Chain(path, names, kn, base, root_blend=(s_rim - 0.1, s_rim + 0.15),
               end_blend=(s_in - 0.3, s_in - 0.05, "Head"))
    for j in range(4):
        R.add(names[j], "Cuff" if j == 0 else names[j - 1], ch.at(kn[j]), ch.at(kn[j + 1]), "neck", index=j + 1)
    R.add("Head", "Neck4", ch.at(kn[4]), tg_head["snout"], "head")
    R.eye_parent = "Head"

    def field(p):                       # near the neck (above the rim): the neck's own chain
        q = Vector(p)
        if q.z > h - 0.1:
            s = float(ch.arc_of([tuple(q)])[0])
            if (ch.at(s) - q).length < 0.75:
                return ch.weights(q, s)
        return base(q)
    R.field = field
    R.put([neck] + R.idx("belly"), ("chain", ch))
    lo, hi = c.face_range
    R.put(R.idx("head nostril smile cheek crest ear"), ("bone", "Head"))
    R.put([i for i in range(lo, hi) if R.info["names"][i] in ("eye", "eyerim", "glint")], ("bone", "Head"))
    R.put(R.idx("spine"), ("stuck", None))
    # the suds puddle and what rises out of it stay on the floor
    pc = Vector(R.info["tags"][R.idx("puddle")[0]]["centre"])
    R.add("Lake", "Root", (pc.x, pc.y, 0.0), (pc.x, pc.y, 0.4), "ground")
    R.put(R.idx("puddle foam bubble") + R.idx("glint", "feat", lambda q: q.z < 1.5), ("bone", "Lake"))
    for k, i in enumerate(R.idx("hump")):
        ap = [Vector(p) for p in R.info["tags"][i]["path"]]
        foot = (ap[0] + ap[-1]) / 2
        R.add(f"Hump{k + 1}", "Lake", (foot.x, foot.y, 0.0), ap[len(ap) // 2], "hump", index=k + 1)
        R.put([i], ("bone", f"Hump{k + 1}"))
    R.put(R.idx("humpfin"), ("near", "Hump"))
    tp = [Vector(p) for p in R.info["tags"][R.idx("tail")[0]]["path"]]
    R.add("Tail", "Lake", tp[0], tp[-1], "tail")
    R.put(R.idx("tail"), ("bone", "Tail"))


def _shockini(R):
    _hat(R, "tuft hairburst hairburst_core spark", "Cuff")
    R.put(R.idx("statichair statichair_core bolt"), ("stuck", None))
    R.put(R.idx("eyecover pinpupil pinglint"), ("eye",))


def _lintlord(R):
    _hat(R, "crown crownrim crownball gem velvet capball", "Cuff")
    R.put(R.idx("ruff"), ("bone", "Cuff"))
    R.put(R.idx("wisp wisp_core"), ("stuck", None))


def _lost(R):
    ids = R.idx("question qcore qdot qglint qhalo")
    lo, hi, cen = R.lo(ids), R.hi(ids), R.cen(ids)
    R.add("Question", "Cuff", (cen.x, cen.y, lo.z), (cen.x, cen.y, hi.z), "accessory")
    R.put(ids, ("bone", "Question"))
    R.put(R.idx("tear teartip tearglint"), ("stuck", R.cen(R.idx("tear"))))


def _puppet(R):
    c, h = R.c, R.c.h
    top_z = c.ey - c.eye_rim_r - 0.08         # sockfeat_c.feat_puppet: the mouth's top edge,
    w0, depth = 0.56, 0.78                     # its half width and depth (the lips go 6% wider)

    def top(u):
        return top_z - 0.06 * (1 - (u / w0) ** 2)

    def bot(u):
        return top_z - depth * max(1 - (u / w0) ** 2.4, 0.0) ** 0.55

    # the hinge sits 2 units behind the mouth, so turning the Jaw about +X (up to ~8 deg) drops the
    # lower jaw nearly straight down (a slide down its -Y does the same); a closer hinge swings the
    # lip in or out of the face
    zm = top_z - depth / 2
    R.add("Jaw", "Leg4", (0.0, 2.0, zm), (0.0, 2.0, top_z + 0.3), "jaw", hint=dict(turn=8, slide=0.3))
    base = R.base

    def jaw(p):
        """The Jaw's share: 0 on the mouth's top edge, rising LINEARLY to 1 on its bottom edge (the
        mouth plates have vertices only on those two edges, so the skin under them must move the
        same linear way or it pokes through), 1 on the chin, fading out below it and to the sides."""
        x, y, z = p
        fr = _smooth((-y - 0.1) / 0.3)                          # the front only
        if fr <= 0.0:
            return 0.0
        u = min(abs(x), w0)
        zt, zb = top(u), bot(u)
        a = min(max((zt - z) / max(zt - zb, 0.1), 0.0), 1.0)
        b = 1.0 - _smooth((zb - 0.1 - z) / 0.3)                 # fading out under the lower lip
        lat = 1.0 - _smooth((abs(x) - (w0 * 1.06 - 0.04)) / 0.2)
        return a * b * lat * fr

    def field(p):
        j = jaw(p)
        return _mix(base(p), {"Jaw": 1.0}, j) if j > 0.0 else base(p)
    R.field = field
    R.put(R.idx("tongue crease"), ("bone", "Jaw"))
    for i in R.idx("tooth tooth_ink"):        # the upper teeth stay with the head
        R.put([i], ("stuck", R.cen([i]), "base"))
    R.put(R.idx("button buttonedge buttonhole"), ("bone", "Leg4"))
    _hat(R, "yarnbase curl curl_core", "Cuff")
    R.put(R.idx("yarn yarn_core"), ("tether", "Hat", h, h - 0.45))


def _plain(*rules):
    def fn(R):
        for names, target in rules:
            R.put(R.idx(names), target)
    return fn


TYPES = {
    "Tubolino": _plain(),
    "AnkleBiter": _anklebiter,
    "CrustyCrew": _plain(("flap", ("bone", "Cuff")), ("crumb", ("stuck", None))),
    "GymGary": _plain(("drop", ("stuck", None))),
    "Argylo": _argylo,
    "ToeToe": _toetoe,
    "Sockrates": _sockrates,
    "KneeHigh": _plain(),
    "Slipperino": _plain(("fluff", ("bone", "Cuff"))),
    "Compressio": _plain(("sweat", ("stuck", None))),
    "Sockhopper": _sockhopper,
    "DJDryer": _djdryer,
    "Socktopus": _socktopus,
    "Sockington": _sockington,
    "Stinkolino": _stinkolino,
    "SockNess": _sockness,
    "Shockini": _shockini,
    "Lintlord": _lintlord,
    "Zillionaire": _zillionaire,
    "LostSock": _lost,
    "PuppetSupreme": _puppet,
}


def rig_rules(tid):
    """The per-type function for `tid`: TYPES above, else the RIG table of the type's own sockfeat
    module (the second wave keeps its rigging next to its features), else just the shared skin."""
    if tid in TYPES:
        return TYPES[tid]
    import socks
    return getattr(socks.feature_module(tid), "RIG", {}).get(tid) or _plain()


def plan(body):
    """The Rig (bones + piece assignments) for a sock body built by socks.build_sock."""
    import socks as S
    c = S.CTX[body.name]
    R = Rig(c, body, K.PIECE_MAP[body.name])
    R.standard_bones()
    rig_rules(c.tid)(R)               # may move the eye parent (SockNess: Head) or the cuff bone
    R.eye_bones()
    R.default_assign()
    return R


# ------------------------------------------------------------------ armature + weights
def _roll_ref(b):
    axis = (b.tail - b.head).normalized()
    ref = FRONT - axis * FRONT.dot(axis)
    if ref.length < 0.35:
        ref = UP - axis * UP.dot(axis)
    return ref.normalized()


def build_armature(name, bones):
    arm = bpy.data.armatures.new(name)
    ao = bpy.data.objects.new(name, arm)
    K.link(ao)
    vl = bpy.context.view_layer
    for o in vl.objects:
        o.select_set(False)
    vl.objects.active = ao
    bpy.ops.object.mode_set(mode="EDIT")
    for b in bones.values():
        eb = arm.edit_bones.new(b.name)
        eb.head, eb.tail = b.head, b.tail
        eb.use_deform = b.role != "root"
    for b in bones.values():
        eb = arm.edit_bones[b.name]
        if b.parent:
            eb.parent = arm.edit_bones[b.parent]
            eb.use_connect = False
        eb.align_roll(_roll_ref(b))
    bpy.ops.object.mode_set(mode="OBJECT")
    arm.display_type = "STICK"
    return ao


def _skin(obj, ao, W):
    for k, w in enumerate(W):
        for b, v in w.items():
            vg = obj.vertex_groups.get(b) or obj.vertex_groups.new(name=b)
            vg.add([k], v, "REPLACE")
    mod = obj.modifiers.new("Armature", "ARMATURE")
    mod.object = ao
    mod.use_vertex_groups = True
    # parented to the armature (the glTF exporter's canonical skinned-mesh layout; the armature sits
    # at the origin unrotated, so nothing moves)
    mw = obj.matrix_world.copy()
    obj.parent = ao
    obj.matrix_parent_inverse = ao.matrix_world.inverted()
    obj.matrix_world = mw


def rig_sock(objs):
    """Adds `<Name>_Rig` and skins the body and the outline (objs from socks.build_sock, after the
    bake). Returns (armature object, Rig)."""
    body = objs[0]
    outline = next(o for o in objs if o.name == body.name + "_Outline")
    R = plan(body)
    W = R.all_weights()
    # the outline: the very same weights as the body vertex it was inflated from
    WO = [None] * len(outline.data.vertices)
    for pi, s, n in R.info["outline"]:
        br = R.info["body"][pi]
        if br is not None:
            for k in range(n):
                WO[s + k] = W[br[0] + k]
        else:      # outline-only pieces: weighted like a piece of their own
            co = np.array([tuple(outline.matrix_world @ outline.data.vertices[s + k].co) for k in range(n)])
            for k, w in enumerate(R.piece_weights(pi, co)):
                WO[s + k] = _finalise(w)
    assert all(w is not None for w in WO), "outline vertices without weights"
    ao = build_armature(body.name + "_Rig", R.bones)
    _skin(body, ao, W)
    _skin(outline, ao, WO)
    for o in objs[2:]:              # glow parts riding on the sock (none yet): rigid, by position
        if o.type == "MESH" and not o.name.endswith(("_Base", "_Unit", "_Pin")):
            cen = sum((o.matrix_world @ v.co for v in o.data.vertices), Vector()) / max(len(o.data.vertices), 1)
            _skin(o, ao, [{R.dominant(cen): 1.0}] * len(o.data.vertices))
    R.W, R.WO = W, WO
    return ao, R


# ------------------------------------------------------------------ the generated Luau config
def bone_table(R):
    """[(name, fields)] in hierarchy order (parents first); fields in the order the Luau file
    writes them (role, index, seg, parent, length, then any hints)."""
    out, done = [], set()
    pending = list(R.bones.values())
    while pending:
        for b in list(pending):
            if b.parent is None or b.parent in done:
                f = [("role", b.role), ("index", b.index), ("seg", b.seg), ("parent", b.parent),
                     ("length", round(b.length, 2))] + sorted(b.hint.items())
                out.append((b.name, [(k, v) for k, v in f if v is not None]))
                done.add(b.name)
                pending.remove(b)
    return out


LUAU_HEADER = """--!strict
-- SockRigConfig: the skeleton inside every sock mesh (assets/meshes/steal-a-sock/socks/*.glb).
-- GENERATED by tools/blender/build_all.py (rigging.py) - do not edit by hand. Re-run
-- `python tools/blender/build_all.py --rig-config` after changing tools/blender/rigging.py.
--
-- Each GLB carries ONE skeleton, used by both the body and its _Outline hull (one glTF skin);
-- Roblox imports the joints as Bone instances with these names. Lengths are in studs at
-- SockScale 1 (the game scales socks x2, bones included). Left and right halves are mirror
-- images (x -> -x) with the same bones and lengths, so each type has one entry.
--
-- Bone axes: local +Y runs along the bone (head -> tail); local +Z points to the sock's front
-- (the face, model +Z) as far as the bone allows; X = Y x Z. Eye and Monocle bones point out of
-- the face, so their +Z is up instead. Root, Leg, Cuff and Jaw bones have no rest rotation: their
-- axes are the model's axes, so turning one about +X curls the part above it toward the face.
--
-- Roles:
--   root       the model origin (_Base marker); never weighted
--   leg        index 1-4 from the ankle up; Leg4 is the face block (it starts just under the
--              eyes, so the face never bends). Tested clean: 15 deg per joint bends (60 deg curls,
--              S-curves); twists about a bone's own Y up to ~10 deg per joint (Argylo's diamond
--              decals flicker past ~20). Singles (Socktopus, LostSock) bend through a wide sack:
--              keep their joints under ~10 deg each
--   cuff       the top band and rolled lip (child of Leg4); Sockington's helm holds it still
--   foot, toe  the foot from the ankle, the toe cap (footed socks only)
--   eye        index 1-2 (viewer's left first): only the pupil rides it - spin it about its own
--              Y to roll the pupil round the googly eye
--   hat        whatever sits on the head (top hat, crown, helm, headphones, wreath, hair, mop);
--              tight ones (Sockington's helm, Sockrates' wreath) want small tilts (< ~8 deg)
--   jaw        turn about +X by up to `turn` degrees, or slide down (local -Y) by up to `slide`
--              studs, to open (PuppetSupreme) or chomp (AnkleBiter's fangs)
--   pogo       Sockhopper's stick (child of Root, pivot at its rubber tip)
--   tentacle   index = tentacle 1-6, seg = 1-3 from the sack to the tip
--   neck, head SockNess: Neck1-4 out of the opening, then the Head (eyes ride on it)
--   digit      ToeToe's five toes (1 = big toe), children of Toe
--   fly        Stinkolino's flies (children of Root: they buzz on their own)
--   ground     stays on the floor (SockNess' suds puddle); hump (index), tail ride on it
--   accessory  monocle, beard, armour, dryer-sheet cape, bills, question mark, stink cloud, rose,
--              fork
--   dangle     a floppy hanging part that swings with the sock's motion: index = which part,
--              seg = 1.. from where it hangs to its tip (nightcap, headband tails, cape halves,
--              bell, earring, hat tips, lappets, a dragon's tail, loose bandage ends); `swing` =
--              the most it bends cleanly per bone (degrees)
--   spring     a short stiff part that wobbles on a spring (hair curl, antenna, moustache);
--              `wobble` = the most it tilts cleanly (degrees)
--   wing       index 1-2 (viewer's left first): flaps about its own Y; `flap` = the most it
--              opens or closes cleanly (degrees)
--   jet        a jetpack nozzle (index 1-2): local +Y points out of the nozzle, for a flame
"""


def _luau_value(v):
    if isinstance(v, str):
        return '"' + v + '"'
    return f"{v:g}" if isinstance(v, float) else str(v)


def write_luau_config(path, tables, order):
    """tables: {key: bone_table}; key = type id (or "<id>_L" / "<id>_R" if the halves differ)."""
    hints = sorted({k for key in order for _n, f in tables[key] for k, _v in f
                    if k not in ("role", "index", "seg", "parent", "length")})
    lines = LUAU_HEADER.rstrip("\n").split("\n") + [
        "",
        "export type BoneInfo = {",
        "\trole: string,",
        "\tindex: number?,",
        "\tseg: number?,",
        "\tparent: string?,",
        "\tlength: number,",
    ] + [f"\t{k}: number?," for k in hints] + [
        "}",
        "",
        "local SockRigConfig = {}",
        "",
        "-- the leg chain from the ankle up; Cuff hangs off Leg4",
        'SockRigConfig.Chain = { "Leg1", "Leg2", "Leg3", "Leg4" }',
        "",
        "SockRigConfig.Types = {",
    ]
    for key in order:
        lines.append(f"\t{key} = {{")
        for name, fields in tables[key]:
            lines.append(f"\t\t{name} = {{ " + ", ".join(f"{k} = {_luau_value(v)}" for k, v in fields) + " },")
        lines.append("\t},")
    lines += ["} :: { [string]: { [string]: BoneInfo } }", "", "return SockRigConfig", ""]
    with open(path, "w", newline="\n") as f:
        f.write("\n".join(lines))


# ------------------------------------------------------------------ test poses (preview.py --pose)
# bone -> [(world axis, degrees)] applied in the bone's rest frame; "side" axes flip with the sock's
# side (d), so a pose looks the same on L and R. +X curls the top toward the face (front).
POSES = {
    "rest": {},
    "curl": {f"Leg{k}": [((1, 0, 0), 15)] for k in (1, 2, 3, 4)},
    "scurve": {"Leg1": [((0, 1, 0), 16)], "Leg2": [((0, 1, 0), 16)], "Leg3": [((0, 1, 0), -18)],
               "Leg4": [((0, 1, 0), -18)]},
    "foot": {"Foot": [(("side", 0, 1, 0), 25)], "Toe": [(("side", 0, 1, 0), 35)]},
    "cuff": {"Cuff": [((0, 1, 0), 32), ((1, 0, 0), -15)]},
    "extras": {"Hat": [((0, 1, 0), 18), ((1, 0, 0), 10)], "Jaw": [((1, 0, 0), 7)], "Monocle": [((0, 0, 1), 25)],
               "Pogo": [((0, 1, 0), 10)], "Beard": [((1, 0, 0), 14)], "Armor": [((1, 0, 0), 10)],
               "Cape": [((1, 0, 0), 30)], "Bills": [((0, 0, 1), 40)], "Question": [((0, 1, 0), 20)],
               "Stink": [((0, 1, 0), -20)], "Eye1": [("own", 120)], "Eye2": [("own", -90)],
               "Tail": [((1, 0, 0), 25)], "Hump1": [((0, 1, 0), 12)], "Lake": [],
               "Neck1": [((1, 0, 0), 10)], "Neck2": [((0, 1, 0), 15)], "Neck3": [((0, 1, 0), 12)],
               "Neck4": [((1, 0, 0), -10)], "Head": [((0, 0, 1), 25)],
               **{f"Toe{k}": [(("side", 0, 1, 0), 30 if k % 2 else -20)] for k in range(1, 6)},
               **{f"Tent{i}_{j}": [((1, 0, 0), 22 if i % 2 else -22)] for i in range(1, 7) for j in (1, 2, 3)},
               **{f"Fly{k}": [((0, 0, 1), 30)] for k in (1, 2, 3)},
               # the second wave (sockfeat_d / sockfeat_e): dangles swing, springs tilt, wings flap
               # about their hinge (own Y), jets stay put
               "Bow": [((0, 1, 0), -15)], "Paci": [((1, 0, 0), 5)], "Curl": [((0, 1, 0), 20)],
               "Bell": [((1, 0, 0), 30)], "Earring": [((1, 0, 0), 30)], "Stache": [((0, 1, 0), 10)],
               "Fork": [((0, 1, 0), 10)], "Antenna": [((1, 0, 0), 25)], "Rose": [((0, 1, 0), 10)],
               **{f"Cap{k}": [((0, 1, 0), 20)] for k in (1, 2, 3)},
               **{f"Noodle{k}": [((1, 0, 0), 25)] for k in (1, 2)},
               **{f"HatTip{k}": [((1, 0, 0), 20)] for k in (1, 2)},
               **{f"Tail{k}": [((0, 0, 1), 20)] for k in (1, 2, 3)},
               **{f"Lappet{k}": [((1, 0, 0), 20)] for k in (1, 2)},
               **{f"Wrap{k}": [((1, 0, 0), 25)] for k in (1, 2)},
               "Wing1": [("own", 30)], "Wing2": [("own", -30)],
               **{f"Band{i}_{j}": [((0, 0, 1), 25 if i == 1 else -25)] for i in (1, 2) for j in (1, 2)},
               **{f"Cape{i}_{j}": [((1, 0, 0), 20), ((0, 0, 1), 15 if i == 1 else -15)]
                  for i in (1, 2) for j in (1, 2)}},
}


def apply_pose(ao, pose, d=1.0):
    """Poses the armature object `ao` (rotations only) with a POSES entry."""
    for pb in ao.pose.bones:
        pb.rotation_mode = "QUATERNION"
        pb.rotation_quaternion = (1, 0, 0, 0)
        pb.location = (0, 0, 0)
    for name, rots in pose.items():
        pb = ao.pose.bones.get(name)
        if pb is None:
            continue
        rest = pb.bone.matrix_local.to_3x3()
        q = Matrix.Identity(3)
        for axis, deg in rots:
            if axis == "slide":                                    # move along the bone (local Y)
                pb.location = (0.0, deg, 0.0)
                continue
            if axis == "own":
                ax = Vector((0.0, 1.0, 0.0))                       # the bone's own axis, local Y
            elif axis[0] == "local":
                ax = Vector(axis[1:])                              # an axis in the bone's frame
            else:
                if axis[0] == "side":
                    axis = tuple(v * d for v in axis[1:])
                ax = rest.inverted() @ Vector(axis)
            q = Matrix.Rotation(math.radians(deg), 3, ax.normalized()) @ q
        pb.rotation_quaternion = q.to_quaternion()
